apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: db
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: db
  template:
    metadata:
      labels:
        service: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: guests_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
          image: postgres:14-alpine
          imagePullPolicy: Always
          name: db
          volumeMounts:
          - name: persistent-storage
            mountPath: /var/lib/postgresql/data
          ports:
            - containerPort: 5432

      restartPolicy: Always
      volumes:
        - name: persistent-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim