# In db-congif.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    service: db
  name: db-service
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    service: db
