apiVersion: v1
kind: Service
metadata:
  labels:
      service: backend
  name: backend-service
spec:
  type: LoadBalancer
  ports:
    - name: "5000"
      port: 8000
      targetPort: 5000
  selector:
    service: backend